FROM node:4

ADD index.html index.html
ADD expressServer.js expressServer.js
ADD package.json package.json
ADD public public 
ADD node_modules node_modules
ADD webpack.config.production.js webpack.config.production.js

CMD npm run start

EXPOSE 3000
